# Generated by Django 3.0.7 on 2020-08-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsApp', '0007_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
