# Generated by Django 3.0.7 on 2020-08-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsApp', '0002_card_deck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
