# Generated by Django 3.0.7 on 2020-08-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsApp', '0005_auto_20200804_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
    ]
