# Generated by Django 3.0.7 on 2020-08-05 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsApp', '0006_remove_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flashcardsApp.Deck'),
            preserve_default=False,
        ),
    ]
